### ISSUE TITLE
Properties with job namespaces in fissile

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/fissile#369]
- [ ] Remove support for the `configuration.templates` key in fissile role manifests (both global and role based)
- [ ] Remove support for opinions.yaml as well as dark-opinions.yaml

Both templates and opinions will be part of jobs, just like a [deployment manifest](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L117).
The role manifest should look like:

```yaml
---
roles:
- name: nats
  jobs:
  - name: nats
    properties:
      nats:
        password: '"((NATS_PASSWORD))"'
        user: nats
```
